version: "3.9"
services:
  go-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - my_network
    depends_on:
      - mysql

  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge  

volumes:
  mysql_data:
